# Generated by Django 5.1.1 on 2024-10-21 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=30)),
                ('orginalPrize', models.PositiveIntegerField(default=0)),
                ('offerprice', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(max_length=200)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('totalRating', models.IntegerField(default=0)),
            ],
        ),
    ]
