# Generated by Django 5.1.1 on 2024-10-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_cart', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=30)),
                ('offer', models.PositiveIntegerField(default=0)),
                ('Originalprice', models.PositiveIntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
