# Generated by Django 5.1.1 on 2024-10-17 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_user_user_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_register',
        ),
    ]
