# Generated by Django 5.1.1 on 2024-10-19 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Slider',
        ),
    ]
