# Generated by Django 5.1.1 on 2024-10-20 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_rename_model_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
